const SONG = "SONG";
const BIBLE = "BIBLE";
const ANNOUNCEMENT = "ANNOUNCEMENT";
const VIDEO = "VIDEO";
const SLIDESHOW = "SLIDESHOW";
const CONTENT = "CONTENT";

const ITEMTYPES = [SONG, BIBLE, ANNOUNCEMENT, VIDEO, SLIDESHOW, CONTENT];

export { SONG, BIBLE, ANNOUNCEMENT, VIDEO, SLIDESHOW, CONTENT, ITEMTYPES };
